# Generated by Django 4.1 on 2022-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="created",),
        migrations.RemoveField(model_name="profile", name="last_location",),
        migrations.RemoveField(model_name="profile", name="modified",),
        migrations.RemoveField(model_name="profile", name="user",),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
